CREATE TABLE [dbo].[Characters] (
    [Blob]           XML            NOT NULL,
    [Modified]       DATETIME       NOT NULL,
    [Name]           NVARCHAR (255) NOT NULL,
    [Age]            AS             ([dbo].[Character_Age]([Blob])),
    [Alignment]      AS             ([dbo].[Character_Alignment]([Blob])),
    [Appearance]     AS             ([dbo].[Character_Appearance]([Blob])),
    [CarriedMoney]   AS             ([dbo].[Character_CarriedMoney]([Blob])),
    [Charisma]       AS             ([dbo].[Character_Charisma]([Blob])),
    [Companions]     AS             ([dbo].[Character_Companions]([Blob])),
    [Company]        AS             ([dbo].[Character_Company]([Blob])),
    [Constitution]   AS             ([dbo].[Character_Constitution]([Blob])),
    [Dexterity]      AS             ([dbo].[Character_Dexterity]([Blob])),
    [Experience]     AS             ([dbo].[Character_Experience]([Blob])),
    [Gender]         AS             ([dbo].[Character_Gender]([Blob])),
    [Height]         AS             ([dbo].[Character_Height]([Blob])),
    [Intelligence]   AS             ([dbo].[Character_Intelligence]([Blob])),
    [Level]          AS             ([dbo].[Character_Level]([Blob])),
    [Character-Name] AS             ([dbo].[Character_name]([Blob])),
    [Notes]          AS             ([dbo].[Character_Notes]([Blob])),
    [Player]         AS             ([dbo].[Character_Player]([Blob])),
    [Portrait]       AS             ([dbo].[Character_Portrait]([Blob])),
    [StoredMoney]    AS             ([dbo].[Character_StoredMoney]([Blob])),
    [Strength]       AS             ([dbo].[Character_Strength]([Blob])),
    [Traits]         AS             ([dbo].[Character_Traits]([Blob])),
    [Weight]         AS             ([dbo].[Character_Weight]([Blob])),
    [Wisdom]         AS             ([dbo].[Character_Wisdom]([Blob])),
    CONSTRAINT [PK_Characters_NameModified] PRIMARY KEY CLUSTERED ([Name] ASC, [Modified] ASC) WITH (IGNORE_DUP_KEY = ON)
);

